baseurl = "/"
languageCode = "en-us"
title = "Data and Code"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
hasCJKLanguage = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blogs"
    url = "/categories/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/liu-du"
    weight = 4

[params]
    description = "Statistics, Data Science, Data Engineering, Software Engineering"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "haskell"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
